spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate

spring.thymeleaf.cache=true

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
