spring.application.name=PBSTApplication

pokewallet.api.url=https://api.pokewallet.io
pokewallet.api.key=overrideMe

spring.thymeleaf.prefix=file:gemini/templates/
spring.web.resources.static-locations=file:gemini/css/,file:gemini/js/
