spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=validate

spring.thymeleaf.cache=true

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
