spring.datasource.url=jdbc:postgresql://localhost:5432/pbstdb
spring.datasource.username=pbstuser
spring.datasource.password=pbstpassword

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
